### ISSUE TITLE
New Address Format

### ISSUE THREAD

**Issue by 4x7152** [kb-dk/alma_cloud_app_print_user_address#10]
Hi

I'm so glad I've found your app, very nice work!

Could you add the following address format for us:

recipient
line1
line2
line3
line4
line5

I'd really appreciate it!

Thanks and kind regards
Sarah

**Comment by ZahraMousavi** [comment]
Hi Sarah

Sure - How should the order of the rest of the elements be, namely postal_code, city, state_province, and country?

And if may, which library/country are you contacting from?

Best regards
Zahra

**Comment by 4x7152** [comment]
Hi Zahra

Thank you for contacting me ☺

That’s the thing – we don’t want the fields postal_code, city, state_province, and country to be displayed. The addresses of our patrons are put in the address_line fields 1-5 (weird, I know, but it’s a data migration thing).

I’m writing you from the Cantonal Library in Grisons based in Chur, Switzerland ☺

Best
Sarah

Von: ZahraMousavi ***@***.***>
Gesendet: Freitag, 26. August 2022 11:45
An: kb-dk/alma_cloud_app_print_user_address ***@***.***>
Cc: Hartmann Sarah ***@***.***>; Author ***@***.***>
Betreff: Re: [kb-dk/alma_cloud_app_print_user_address] New Address Format (Issue #10)


Hi Sarah

Sure - How should the order of the rest of the elements be, namely postal_code, city, state_province, and country?

And if may, which library/country are you contacting from?

Best regards
Zahra

**Comment by ZahraMousavi** [comment]
Could you please check the new address format and give feedback?

**Comment by 4x7152** [comment]
It’s perfect, thank you very much ☺☺☺

Von: ZahraMousavi ***@***.***>
Gesendet: Freitag, 26. August 2022 13:41
An: kb-dk/alma_cloud_app_print_user_address ***@***.***>
Cc: Hartmann Sarah ***@***.***>; Author ***@***.***>
Betreff: Re: [kb-dk/alma_cloud_app_print_user_address] New Address Format (Issue #10)


Could you please check the new address format and give feedback?

**Comment by ZahraMousavi** [comment]
You are very welcome :-)
