### ISSUE TITLE
Print patron's name and barcode

### ISSUE THREAD

**Issue by kremke** [kb-dk/alma_cloud_app_print_user_address#11]
Hi,

We recently moved from Aleph to Alma and are slowly figuring out how we can recreate in Alma functions that were available in the old system. One of the things we have had many complaints about is the inability in Alma to print a library card for the patrons.  In Aleph there was a function to print the patron's name and barcode on the pocket label part of the labels used for our books:
![20220927_090501](https://user-images.githubusercontent.com/76584888/192496919-72b5f799-e94f-42b1-bad0-4fd8c3d9b8c0.jpg)

During the presentation on Igelu í thought that rather than having to create a new Cloud app for this, perhaps it  would be possible to create a new template in the Print address app that would fetch the patron's name and barcode and print it in the correct location on our label. We are using code 128 for the barcodes.

Do you think this would be possible?

Regards,

Helgi Steindal

**Comment by ZahraMousavi** [comment]
Dear Helgi - Thanks for contacting us. I have talked to my manager about your request, but we think that is not relevant to our address app, which is heavily based on extracting addresses and showing them. 
I am afraid to say that based on the current infrastructure of our app, it won't be possible to add this possibility to it.
Best regards
Zahra

**Comment by kremke** [comment]
Hi Zahra,

Thanks for looking into this for us.

Regards,

Helgi

**Comment by ZahraMousavi** [comment]
Hi Helgi

Sorry, we couldn't help. Hopefully next time :-)

Best regards
Zahra
