### ISSUE TITLE
Can we configure the order of the address elements

### ISSUE THREAD

**Issue by SWITCHconsortium** [kb-dk/alma_cloud_app_print_user_address#5]
This is a neat little app. Thanks for creating it. It would be even better if we could arrange the data elements to follow the address convention of our country. For example, the current format comes out as:

Jane Doe
2178 N Main St
WI 53213 Wauwatosa

but in the United States, we would prefer to print the address following the US convention for addresses:

Jane Doe
2178 N Main St
Wauwatosa, WI 53213

If it is possible for us to have an interface to drag and drop the {{elements}} that would be one option. Otherwise, perhaps you could have a radio button to choose from 2 or more common address styles.

**Comment by EmeliaS** [comment]
Yes, I agree. Our suburbs are showing at the end of the line rather than at the start.
eg:
NSW 2148 Marayong
Rather than 
Marayong, NSW 2148

**Comment by ZahraMousavi** [comment]
Great to hear that other libraries than us can use the App. I will add the issue to our Jira board and we will look at it as soon as possible.
By the way, I am curious to hear which libraries/institutions are you working for?

**Comment by SWITCHconsortium** [comment]
Thanks!

We are  a consortium of 8 small academic libraries in southeastern Wisconsin, United States.

Katie

**Comment by ZahraMousavi** [comment]
Great :-)

I have made a quick fix for USA such that it checks if the country description is "United States" or "The United States"or the country value (short form) is "USA", it changes the order of the elements. 
It is live now. Could you please check if it works some expected?

**Comment by SWITCHconsortium** [comment]
Thanks! It is coming out like this:

Jane Doe
1234 N. Main Street
53213 Milwaukee WI

But in the US, we format the address like this:

Carol Abuya
1234 N. Main Street
Milwaukee, WI 53213

Again – thank you for this.

Katie

**Comment by ZahraMousavi** [comment]
Ok! It seems like your country fields are empty, so the program cannot find out that the country is USA. 
See an example from our Alma: https://snipboard.io/eva8q2.jpg

If you don't have the possibility to fix the country in your data, I can add one additional option in the settings so you can choose your country there?

**Comment by SWITCHconsortium** [comment]
Of course! If you could add the option in the settings to choose your country, that might be best. Even if I get each university to modify their SIS loads, there are probably other schools in the US that also omit the country in their records. Including the ability to select the country in the settings might be good for all future users of the cloud app as well.

Please only tweak when you have time. I don’t want to cause you more trouble – just thought this was a great application that we would use if possible.

Thanks!

Katie

**Comment by EmeliaS** [comment]
> Great to hear that other libraries than us can use the App. I will add the issue to our Jira board and we will look at it as soon as possible.
> By the way, I am curious to hear which libraries/institutions are you working for?

I am at Western Sydney University in Sydney, Australia. 

Emelia

**Comment by ZahraMousavi** [comment]
The good news is that yesterday I got permission from my boss to work on solving the two issues you both have announced besides my other projects. I will try to find a better solution to this problem. 
It is pleasure to be able to give back to the community :-)

**Comment by SWITCHconsortium** [comment]
I am with the SWITCH library consortium – a collection of 8 small academic and seminary libraries in Southeastern Wisconsin.

Katie

**Comment by ZahraMousavi** [comment]
Could you, @SWITCHconsortium and @EmeliaS, please check the new version of the App and give feedback on that?
In the Configuration, there are two options for Address type, one can choose from.

**Comment by SWITCHconsortium** [comment]
Like where you are going with this. There seems to be a problem, though. Please see this video that describes what I am seeing: https://drive.google.com/file/d/1mw_itO0ZHffuxVyuhDJMzKhv4SAH2c_Z/view

Katie

**Comment by EmeliaS** [comment]
I didn't have that problem, but I changed the setting then closed out of the app before trying it. It's an Alma habit I have, any time I change anything in Alma I change, save and reopen. 

However, my issue is that it worked fine when I was logged in as the Admin, but when I changed to a normal user the configuration choice seemed to revert back to the first choice. As a normal user we can't change those settings, should the admin configuration make the change for everyone?

But other than that when it worked it looked great.
Emelia

**Comment by SWITCHconsortium** [comment]
I tested again this morning. When I followed Emelia’s suggestion of making the change and then signing out and signing back in, I was able to “print” the labels with the desired format. I was also able to log out and then log in with a different test user account and the format did not change.

I then repeated the test in another instance we manage and was able to replicate it; however, I realized that in that instance the country is loaded by the SIS so the labels now include the country.

Mary Jones
2875 Wooster Court
Framingham, MA 03897
United States

In the United States, we would not include the country in the address. Is there any way to build the app such that the admin selects the fields they want to print? The Spine-O-Matic Cloud App has this feature:

***@***.***D751FF.AF4F2930]


As you can see, it seems to use this open source text editor: https://www.tiny.cloud/

Alternatively, what would you think of just adding a choice 3 that omits the country field?

Katie

**Comment by EmeliaS** [comment]
> I didn't have that problem, but I changed the setting then closed out of the app before trying it. It's an Alma habit I have, any time I change anything in Alma I change, save and reopen.
> 
> However, my issue is that it worked fine when I was logged in as the Admin, but when I changed to a normal user the configuration choice seemed to revert back to the first choice. As a normal user we can't change those settings, should the admin configuration make the change for everyone?
> 
> But other than that when it worked it looked great.
> Emelia

I checked again this morning and now it all seems to work fine for the normal user. However I noticed the post code has moved in the print out, but is still showing in the correct spot in the config on choice 2?

Patron Name
27 Elizabeth Cres
2199 YAGOONA NSW

instead of 

Patron Name
27 Elizabeth Cres
YAGOONA NSW 2199 

Odd.  
Emelia

**Comment by ZahraMousavi** [comment]
Thank you, both, for your inputs. 

I have noticed the problem you have mentioned before (with the fact that configuration doesn't apply before one closes and opens the App again). I guess Cloud Apps use a kind of caching, but unfortunately I cannot find anything in the documentations about it. I will try to find a solution for this problem.

 @EmeliaS About the question you mentioned earlier:
`However, my issue is that it worked fine when I was logged in as the Admin, but when I changed to a normal user the configuration choice seemed to revert back to the first choice. As a normal user we can't change those settings, should the admin configuration make the change for everyone?`
I would say that since I have added the option to the configuration (the wrench icon) so only Admins can see and change it for everyone. But still caching can be a problem. Clearing the cache is explained here: https://www.namecheap.com/support/knowledgebase/article.aspx/10078/2194/how-to-do-a-hard-refresh-in-chrome-firefox-and-ie/

@EmeliaS I didn't totally understood your last comment. Is it working for you now or you have some kind of issues? Could you explain a bit more?

**Comment by EmeliaS** [comment]
> Thank you, both, for your inputs.
> 
> I have noticed the problem you have mentioned before (with the fact that configuration doesn't apply before one closes and opens the App again). I guess Cloud Apps use a kind of caching, but unfortunately I cannot find anything in the documentations about it. I will try to find a solution for this problem.
> 
> @EmeliaS About the question you mentioned earlier:
> `However, my issue is that it worked fine when I was logged in as the Admin, but when I changed to a normal user the configuration choice seemed to revert back to the first choice. As a normal user we can't change those settings, should the admin configuration make the change for everyone?`
> I would say that since I have added the option to the configuration (the wrench icon) so only Admins can see and change it for everyone. But still caching can be a problem. Clearing the cache is explained here: https://www.namecheap.com/support/knowledgebase/article.aspx/10078/2194/how-to-do-a-hard-refresh-in-chrome-firefox-and-ie/
> 
> @EmeliaS I didn't totally understood your last comment. Is it working for you now or you have some kind of issues? Could you explain a bit more?

Hi,

I cleared my cache and both issues have stopped. It works fine for me from the limited testing i did today as a normal user.

Thanks,
Emelia

**Comment by ZahraMousavi** [comment]
Sounds great Emelia. I hope it works for you, Katie, as well?

**Comment by ZahraMousavi** [comment]
@SWITCHconsortium you were right. There was a bug in the code which was causing the mystic behavior. And now it is fixed :-)

I have also added the possibility to unselect printing the country if you want.

Could you, Emilia and Katie,  test the App and give feedback?

**Comment by SWITCHconsortium** [comment]
Tested and it works well. Thank you!

Can you provide a little clarification on the return address functionality?

Katie

**Comment by SWITCHconsortium** [comment]
Never mind, I realized I just need to use the arrows to scroll to another page in your information.

Katie

From: Katie Utschig
Sent: Thursday, June 3, 2021 8:36 AM
To: kb-dk/alma_cloud_app_print_user_address ***@***.***>; kb-dk/alma_cloud_app_print_user_address ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [kb-dk/alma_cloud_app_print_user_address] Can we configure the order of the address elements (#5)

Tested and it works well. Thank you!

Can you provide a little clarification on the return address functionality?

Katie
