### ISSUE TITLE
Partner address with logo

### ISSUE THREAD

**Issue by EmeliaS** [kb-dk/alma_cloud_app_print_user_address#6]
Hi,

Would it be possible to have the Partner print out show the same as the User option?
I like how the User print out just shows the address and our logo, printing out the return library address and our address (even with a cross through it) may cause issues for our mail system.

Thanks,
Emelia

**Comment by ZahraMousavi** [comment]
Great to hear that other libraries than us can use the App. I will add the issue to our Jira board and we will look at it as soon as possible.

**Comment by ZahraMousavi** [comment]
Hi @EmeliaS . We have added the possibility to choose the address type in the settings (gear icon). 
Could you please test it and give us feedback?

**Comment by EmeliaS** [comment]
Hi @ZahraMousavi 
I've done a bit of testing on it and it works as expected without the logo. But when I add the logo and more than one address the logo moves position for the 2nd, 3rd etc address.  The first logo (top right) is for the first address, and the other logo is for the 2nd address. As you keep adding addresses, the logos keep moving to the left and don't quite align correctly with that address.

![image](https://user-images.githubusercontent.com/84109001/122320364-74040880-cf65-11eb-891b-578a583ea89d.png)

Thanks, Emelia

**Comment by ZahraMousavi** [comment]
Hi Emelia - Thanks for your help! Now the issue should be fixed. I hope you can test again and give your feedback? It would be great if you could print as well and see the result on paper.

**Comment by EmeliaS** [comment]
Hi,
It works great. Thanks for fixing that! I haven't printed it on paper yet, I'll do that when I'm in the office tomorrow, but otherwise it looks great.

**Comment by EmeliaS** [comment]
Hi,
I've printed addresses out on paper and on our label printer today. It looks great. Thanks for all your help!

**Comment by ZahraMousavi** [comment]
Great! And thank you for your help with testing :-)
