### ISSUE TITLE
A request for some small changes or addons

### ISSUE THREAD

**Issue by pedlib** [kb-dk/alma_cloud_app_print_user_address#7]
Could you add an address format with a separate line for the first address line.

recipient
line1 
line2 line3 line4 line5
postal_code city state_province
country

This would make our adress labels easier to read
I downloaded the app from github, made the changes shown and that worked well

When I run the app downloaded from github and
choosse an address and click ”Print 1 user address” it opens the address in a browser AND opens a print window as well, so all I have to do is click print.
However, when I open the app in Alma and click ”Print 1 user address” it only opens the address in a browser window? 

Is it possible to change so the ”CTRL P” command will be sent along also in the published app?
And if possible to add ”Enter” afterwards so the print is sent to the printer right away?

Kind regards
Per Dockweiler

**Comment by ZahraMousavi** [comment]
- I have added the format you needed to the app. Could you please check that it is working properly?

- About the sending print command on page load, it is actually the same code that is used in the production version, but if I remember it correctly, it gets blocked by Exlibris for security purposes.

**Comment by pedlib** [comment]
Dear Zahra

Thanks, it works fine.

But as I am to use it for Danish addresses I would appreciate to have it reversed,
so the print has postal code before city.

Just bad luck that the command is blocked in production.

Kind regards
Per Dockweiler
CBS Library


Fra: ZahraMousavi ***@***.***>
Sendt: 1. februar 2022 10:01
Til: kb-dk/alma_cloud_app_print_user_address ***@***.***>
Cc: Per Dockweiler ***@***.***>; Author ***@***.***>
Emne: Re: [kb-dk/alma_cloud_app_print_user_address] A request for some small changes or addons (Issue #7)


*         I have added the format you needed to the app. Could you please check that it is working properly?

*         About the sending print command on page load, it is actually the same code that is used in the production version, but if I remember it correctly, it gets blocked by Exlibris for security purposes.

-
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkb-dk%2Falma_cloud_app_print_user_address%2Fissues%2F7%23issuecomment-1026611178&data=04%7C01%7C%7Ca0305a54cdf647685c2308d9e5616597%7C875c414e5d004cdbb77adeae5d6ab201%7C1%7C0%7C637793028754997563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jbxy98zMFphgMYVBfm65ps%2B14ZebfhBbRiDFWhZw3h8%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWSOVJ4CCLH4K2SD65TQV6LUY6ONPANCNFSM5NGKGI2Q&data=04%7C01%7C%7Ca0305a54cdf647685c2308d9e5616597%7C875c414e5d004cdbb77adeae5d6ab201%7C1%7C0%7C637793028754997563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XbAqp0xzz8HlnvJoRLE24vzWgYraBBLwo8FwIXOrQk0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca0305a54cdf647685c2308d9e5616597%7C875c414e5d004cdbb77adeae5d6ab201%7C1%7C0%7C637793028754997563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=q29mof6qDG4o4qwjV7QFS2%2FKGeRtzfBfoLnjVspBOmU%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca0305a54cdf647685c2308d9e5616597%7C875c414e5d004cdbb77adeae5d6ab201%7C1%7C0%7C637793028754997563%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BExv%2BeZvo8qRp1K1fE6SKCv9%2BDFlZg5EZZ1wVizGnw0%3D&reserved=0>.

**Comment by ZahraMousavi** [comment]
Dear Per - Now it should be fixed. Could you confirm that, so I close the issue?

**Comment by pedlib** [comment]
Dear Zahra

It's exactly the way we needed.
Thank you for adding the address format for us.

Kind regards
Per Dockweiler
CBS Bibliotek

Fra: ZahraMousavi ***@***.***>
Sendt: 1. februar 2022 11:00
Til: kb-dk/alma_cloud_app_print_user_address ***@***.***>
Cc: Per Dockweiler ***@***.***>; Author ***@***.***>
Emne: Re: [kb-dk/alma_cloud_app_print_user_address] A request for some small changes or addons (Issue #7)


Dear Per - Now it should be fixed. Could you confirm that, so I close the issue?

-
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkb-dk%2Falma_cloud_app_print_user_address%2Fissues%2F7%23issuecomment-1026662135&data=04%7C01%7C%7C0524d5994b4b431543ea08d9e5699430%7C875c414e5d004cdbb77adeae5d6ab201%7C1%7C0%7C637793063903345228%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tYDFNOGANN2kSRvMYnVubZfkEVoYKj1KS9ssH9LYuDg%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWSOVJ72W4U5XB6EREZEOU3UY6VJDANCNFSM5NGKGI2Q&data=04%7C01%7C%7C0524d5994b4b431543ea08d9e5699430%7C875c414e5d004cdbb77adeae5d6ab201%7C1%7C0%7C637793063903345228%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FN0NtI%2BE2gF4qsJlJjHak2KVs%2BObpRxTY41JQKtyXvk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C0524d5994b4b431543ea08d9e5699430%7C875c414e5d004cdbb77adeae5d6ab201%7C1%7C0%7C637793063903345228%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jOI4zBXiwAbYbusoMl9juU2JLey604jQppc3faOuyVI%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C0524d5994b4b431543ea08d9e5699430%7C875c414e5d004cdbb77adeae5d6ab201%7C1%7C0%7C637793063903345228%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=o2iR3%2BOa7XyEDTieoB%2FiQPELRl7PKmAt526ioN5JMr8%3D&reserved=0>.

**Comment by ZahraMousavi** [comment]
Great! You are very welcome :-)
