### ISSUE TITLE
Question: Top Margin & Spacing

### ISSUE THREAD

**Issue by VangelisPalaskas** [kb-dk/alma_cloud_app_print_user_address#8]
Dear @ZahraMousavi,

I hope that you are well. This cloud app seems interesting for our institution (LIBIS - KU Leuven Libraries). I have started experimenting and I had a quick question.

Is it possible for users to configure the Top Margin (or the Spacing) so that we can use the full label?

Preview:
![image](https://user-images.githubusercontent.com/89778038/173378030-6f97bd76-9f2c-450f-9de3-66c361333078.png)

Settings:
![image](https://user-images.githubusercontent.com/89778038/173378130-0d00f59d-12c0-44b9-96bd-8be6bb01ab24.png)

I have printed out some labels and the app works well. However the big top margin limits the font size and/or the logo (logo is not necessary for now). Also there are some blank labels in the preview but they are not really printed out so that is okay. 

Any tip from you will be useful :)

Kind regards,

Vangelis Palaskas.

**Comment by ZahraMousavi** [comment]
Hi Vangelis

That's great to hear that you will be using our App :-)
I have now rephrased/renamed some of the items in the settings and have added some more descriptions to some of them. 
The label option (under the Partner section) that you have been using is not actually meant to be used with users/vendors. You can use the paper section and if you wish to print multiple addresses on one page you can choose the option there.

Please let me know if you can use the App as is or if you need some other options?

**Comment by VangelisPalaskas** [comment]
Thank you very much for your answer and the adjustments @ZahraMousavi. 

Please correct me if I am wrong but this doesn't solve the issue of non-adjustable top margin. The margins in my printer preferences were set to 0 as well but its still the same. I will keep running tests to multiple institutions before implementing the app. However, what we would like as a network of libraries is:

1. Option to adjust the Top Margin to manage better the label space;
2. Option to add a text (e.g. IN TRANSIT) above the address.

This is the label that I try to replicate using the cloud app instead of the desktop app that the library is using:
![image](https://user-images.githubusercontent.com/89778038/173752461-ece63f21-28be-4313-b0ed-b3514eeca03f.png)

Would this be possible?

Thank you in advance.

Vangelis.

**Comment by ZahraMousavi** [comment]
Hi Vangelis


I have released a new version of the App with some more options in the settings, including address top margin and text on top of the address.
Could you please check it and give me feedback?

Best
Zahra



________________________________

**Comment by VangelisPalaskas** [comment]
Hi Zahra,

Thank you very much for taking into account my question and for adding the new features! Using the preview I can see that the app is already improved 👍 . 

I can only see a small issue with the first label that adds an extra top margin:
![image](https://user-images.githubusercontent.com/89778038/174783955-f04ed7e0-33a4-4291-8b22-b026bd2c3528.png)

I have set the Paper Margin to 0 and the Address top margin to 0.1 so I cannot explain why this happens in the first label only. However, I will perform some tests.

Testing & Feedback: 
I have an appointment tomorrow with one of our KU Leuven libraries to test the app in practice. I will do some testing and come back to you by the end of the week with some feedback :).

Thanks again.

Kind regards,

Vangelis.

**Comment by ZahraMousavi** [comment]
Hi again - Could you please send a screenshot of your settings, so I can maybe recreate it? And just to make sure, have you looked into your printer settings as well?

________________________________

**Comment by VangelisPalaskas** [comment]
Sure :)

Here are both the settings of the Print Addresses Cloud App (left) and the Printer Preferences (right):

![image](https://user-images.githubusercontent.com/89778038/174802390-59cf9c58-07d9-4508-a799-82a0ed9f03b2.png)

**Comment by VangelisPalaskas** [comment]
Hi @ZahraMousavi,

I did some testing today. I found out that this small 'bug' only happens if someone sets configures the **Top Margin: 0**. The issue is solved if someone adds a small Top Margin (e.g. 0.1). You might want to fix the small issue but it is not urgent as it already works👍.

![image](https://user-images.githubusercontent.com/89778038/175029712-565c5066-6d6c-4842-ba3b-adca73e3345e.png)

On the other hand I encountered another small issue. I did some tests in the library and the text was cut on the left side. They use another label type so changing the printer preferences wouldn't be optimal because they use the same changes for the barcode labels. I solved the issue by increasing the Paper Margin for 0 to 2 in the cloud app. However, I lost a lot of space from the top. 

![image](https://user-images.githubusercontent.com/89778038/175032102-9cd9e3e6-dc48-4e92-a68f-f5ae0c86afb7.png)

Thus, I would like to ask you: 
Would be possible to add a 'Left Padding' (or a 'Left Margin') feature to adjust the text a bit on the right like in SpineOMatic?

You already helped a lot. It is not very urgent but it would be nice to have.

Kind regards,

Vangelis.

**Comment by VangelisPalaskas** [comment]
Good morning @ZahraMousavi. 

Maybe this picture is more clarifying regarding the request for Left Padding (or Left Margin). As aforementioned, I used the Paper Margin to solve the issue but it is not ideal as it creates a huge Top Margin:

![image](https://user-images.githubusercontent.com/89778038/175247135-a7d971e7-9663-4293-a9bd-3072023efc6a.png)

Thank you once more for looking into it.

**Comment by ZahraMousavi** [comment]
Hi Vangelis


I have released a new version with address margins and I hope it can solve the problem.

I am going on vacation and will be back 30th of Jun.


Best

Zahra

________________________________

**Comment by VangelisPalaskas** [comment]
Many thanks @ZahraMousavi,

It looks super! I will do some tests (if necessary) and come back to you but it looks good.

Have a great holiday time :).

Kind regards,

Vangelis.
