### ISSUE TITLE
label format for users/vendors

### ISSUE THREAD

**Issue by pedlib** [kb-dk/alma_cloud_app_print_user_address#9]
Dear Zahra

With the latest update the option to print for users/vendors as label (10cm x 5,5cm) disappeared.
The option to choose paper size doesn´t include a label size.
Could you please add label (10cm x 5,5cm) as an option for users/vendors again

Kind regards
Per Dockweiler
CBS Library

**Comment by ZahraMousavi** [comment]
Dear Per

I have added an option to the paper size with the label size(10cm x 5,5cm). 
Does it solve the problem or do other options need to be added?
